version: 1.0.{build}
configuration: Release
init:
- git config --global core.autocrlf true
build_script:
- cd build
- powershell -Command .\build.ps1 -VisualStudioVersion "12.0" -Verbosity minimal -Logger "${env:ProgramFiles}\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cd ..
test_script:
- vstest.console /logger:Appveyor "C:\projects\dotnet-threading\Tests\UnitTest.RackspaceThreading\bin\net35-client\%CONFIGURATION%\UnitTest.RackspaceThreading.net35.dll"
- vstest.console /logger:Appveyor "C:\projects\dotnet-threading\Tests\UnitTest.RackspaceThreading\bin\net40-client\%CONFIGURATION%\UnitTest.RackspaceThreading.net40.dll"
- vstest.console /logger:Appveyor "C:\projects\dotnet-threading\Tests\UnitTest.RackspaceThreading\bin\net45\%CONFIGURATION%\UnitTest.RackspaceThreading.net45.dll"
- vstest.console /logger:Appveyor "C:\projects\dotnet-threading\Tests\UnitTest.RackspaceThreading\bin\portable-net40\%CONFIGURATION%\UnitTest.RackspaceThreading.portable_net40.dll"
- vstest.console /logger:Appveyor "C:\projects\dotnet-threading\Tests\UnitTest.RackspaceThreading\bin\portable-net45\%CONFIGURATION%\UnitTest.RackspaceThreading.portable_net45.dll"
